#run_logged $PALAWAN_INSTALL/packages/drivers/amd-gpu-cpu.sh
#run_logged $PALAWAN_INSTALL/packages/yay.sh
#run_logged $PALAWAN_INSTALL/packages/base.sh
#run_logged $PALAWAN_INSTALL/packages/hyprland.sh
#run_logged $PALAWAN_INSTALL/packages/nodejs.sh
#run_logged $PALAWAN_INSTALL/packages/ai-cli/codex-cli.sh
#run_logged $PALAWAN_INSTALL/packages/ai-cli/gemini-cli.sh
#run_logged $PALAWAN_INSTALL/packages/ai-cli/claude-cli.sh
#run_logged $PALAWAN_INSTALL/packages/fonts.sh
#run_logged $PALAWAN_INSTALL/packages/web-browser.sh
run_logged $PALAWAN_INSTALL/packages/editors.sh
#run_logged $PALAWAN_INSTALL/greeter/sddm/sddm.sh